### PR TITLE
person: best practify isBannerID

### LINKED ISSUE #43: Best-practicify the bannerID check
A couple things here:

We should rename `IsBannerID` to `isBannerID` so it's clearer it's an internal function, not meant for external use.  This is one of the annoying idiosyncracies in Go is the magic variable / function names: if capitalized, they're *implicitly* exported (as if you declared them `public` in other languages).

We should ensure the banner id is precisely 9 digits, not just contains 9 digits, e.g., `^95[0-9]{7}$`.  We can also replace `[0-9]` with `\d` to make the regex a little smaller and clearer.

We should get the regex into a package-level variable.  `MustCompile` will crash if the regex is invalid, but it won't crash until the call happens.  When a variable is declared at the package level, on the other hand, its code is called when the application starts up, which means we get immediate feedback for regexes and similar things.  For example, in RAIS, we do this: https://github.com/uoregon-libraries/rais-image-server/blob/develop/src/cmd/rais-server/image_handler.go#L37-L42.  A bad regex there will crash any tests in that package, even if the tests aren't validating that particular line of code.

### PR DESCRIPTION
**Pull request by lsat12357**
fixes #43

### CODE REVIEW

File: src/person/person.go [hunk 1]
```diff
@@ -77,9 +77,11 @@ func (p *Person) CanBeGE() bool {
 	return false
 }
 
-// IsBannerID returns true if id is a 95 number
-func IsBannerID(stringID string) bool {
+// BannerIDRegex pattern for use in match in isBannerID()
+var BannerIDRegex = regexp.MustCompile("95[0-9]{7}$")
```
Comment (jechols) [inline src/person/person.go]: Toss in a caret at the beginning and this is perfect
